### ISSUE TITLE
##[warning]Unexpected input 'GITHUB_TOKEN'

### ISSUE THREAD

**Issue by IgnusG** [squalrus/merge-bot#28]
**Describe the bug**
The GITHUB_TOKEN is not recognized as input.

**To Reproduce**
1. Use action
2. Set:
```
- uses: squalrus/merge-bot@v0.4.1
   with:
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      method: merge
      labels: version-ready
```

**Expected behavior**
Uses GITHUB_TOKEN as auth.

**Screenshots**
![image](https://user-images.githubusercontent.com/6438760/82589823-01c3c780-9b9d-11ea-8986-63c5c73c54f6.png)

The input is being read here: https://github.com/squalrus/merge-bot/blob/1083cc7ea933ace2ec2baa32deccb3461da88f8f/index.js#L19

But needs to be specified in `action.yml` for github to recognize it here:
https://github.com/squalrus/merge-bot/blob/1083cc7ea933ace2ec2baa32deccb3461da88f8f/action.yml#L7-L30
