### ISSUE TITLE
GITHUB_TOKEN is unknown as a parameter

### ISSUE THREAD

**Issue by orj** [squalrus/merge-bot#30]
When running the action it outputs:
```
##[warning]Unexpected input 'GITHUB_TOKEN', valid inputs are ['test', 'labels', 'blocking-labels', 'reviewers', 'checks_enabled', 'method']
```

**To Reproduce**
Configure the action workflow:
```
name: Merge Bot

on:
  pull_request:
    types: [labeled, unlabeled, ready_for_review, review_request_removed, review_requested, synchronize]
  pull_request_review:
    types: [dismissed, submitted]

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        reviewers: true
        labels: "pr:merge-on-approval"        
        checks_enabled: true
        method: merge
```

**Expected behavior**
That it not spit out warnings.  I think you should change
```
        const token = core.getInput('GITHUB_TOKEN');
```
to:
```
        const token = process.env['GITHUB_TOKEN'] || '';
```
And change your configuration example to:
```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        test: true
        reviewers: true
```
etc.
