### ISSUE TITLE
Is there a way to merge without labeling?

### ISSUE THREAD

**Issue by Undeadlol1** [squalrus/merge-bot#45]
My team doesn't use labels. Currently bot doesn't want to merge PRs without labels.

What i want to achieve:

In our repo if we have at least one approve on a PR it is considered ready to merge. Can I configure this bot to automatically update and merge PR after any approval from any reviewer? Without using labels of course.

**Comment by squalrus** [comment]
Thanks for reaching out! In your config `.yml` have you tried setting `reviewers` to `true` and `labels` blank?

```
reviewers: true
labels: 
```

I too would expect that work, if not it's a scenario we should support.

**Comment by Undeadlol1** [comment]
```
name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: PR Merge Bot
        uses: squalrus/merge-bot@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: null
          blocking_labels: do not merge
          checks_enabled: true
          method: squash
          delete_source_branch: true
```

I tried:
removing "labels" line
make it empty
add "~" to it

None of it worked.
Also, seems like this field is required. Github editor suggests that this field can not be empty.

![image](https://user-images.githubusercontent.com/4124323/96825018-a21e6080-1449-11eb-855c-95b3ea9f6eb3.png)
