### ISSUE TITLE
Feature: on commit, remove label(?) or Re-request review(?)

### ISSUE THREAD

**Issue by squalrus** [squalrus/merge-bot#7]

**Comment by aaron-trout** [comment]
You can make this happen by comboing this with another action. I have the "dismiss pull reviews when new commits are added" thing in the repo settings checked, then using the following action to remove the "ready" label:

```
name: Remove ready label
on:
  pull_request_review:
    types:
      - edited
      - dismissed
jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: remove ready label
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: ready
          type: remove
```
